[keys]
#This hash is intended to separate the entered login and password
splitter="875ef5165a253cdd53d469fdc33a4bcc"
#jsONweBToken_secretKEy_ser_vi_ced_e_sk
secret_hash="58149bc67f649adef725f93b5233c927"
